jog_arm_server:
  cmd_in_topic:  jog_arm_server/delta_jog_cmds
  cmd_frame:  temoto_end_effector  # TF frame that incoming cmds are given in
  incoming_cmd_timeout:  0.25  # Stop jogging if X seconds elapse without a new cmd
  joint_topic:  joint_states
  move_group_name:  manipulator
  singularity_threshold:  6 #3.5
  hard_stop_singularity_threshold: 18. # Stop when the condition number hits this
  cmd_out_topic:  herbie/joint_trajectory
  planning_frame:  world
  low_pass_filter_coeff:  2.  # Larger c --> trust the filtered data more, trust the measurements less.
  pub_period:  0.02  # 1/Nominal publish rate [seconds]
  scale:
    linear:  0.002
    rotational:  0.005

# This node republishes joystick messages for the arm jogger.
joy_to_twist:
  cmd_frame:  temoto_end_effector